version: 2

sources:
  - name: jaffle_shop
    description: This is a replica of the Postgres databse used by our app
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: One record per customer.
      - name: orders
        description: One record per order. Includes cancelled and deleted orders.

  - name: stripe
    description: This is a replica of the Stripe database used by our app
    database: raw
    schema: stripe
    freshness:
          warn_after: {count: 7, period: day}
          error_after: {count: 10, period: day}
    loaded_at_field: _BATCHED_AT
    tables:
      - name: payment
        description: one record per payment.